In [42]:
import pandas as pd
import os

In [45]:
cases = pd.read_csv("../../../data/stage_I/covid_confirmed_usafacts.csv", delimiter=",")
population = pd.read_csv("../../../data/stage_I/covid_county_population_usafacts.csv", delimiter=",")
deaths = pd.read_csv("../../../data/stage_I/covid_deaths_usafacts.csv", delimiter=",")

In [46]:
cases[]

,countyFIPS,County Name,State,StateFIPS,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,...,2021-02-02,2021-02-03,2021-02-04,2021-02-05,2021-02-06,2021-02-07,2021-02-08,2021-02-09,2021-02-10,2021-02-11
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,5723,5753,5811,5824,5856,5869,5881,5910,5930,5970
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,18344,18418,18494,18568,18668,18723,18763,18824,18888,18960
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,1966,1981,1989,1994,2002,2008,2008,2019,2024,2030
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,2319,2321,2327,2331,2334,2339,2346,2362,2368,2377
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,3510,3519,3529,3533,3537,3537,3559,3561,3571,3586
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,3151,3161,3199,3219,3233,3238,3257,3266,3266,3266
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,1975,1981,1984,1984,1984,1984,1988,1994,1995,1995
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,868,869,870,870,870,870,870,870,871,872
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,611,612,613,613,614,616,618,618,618,618

In [61]:
len(cases[1:]['countyFIPS'].unique())

3143

In [48]:
deaths

,countyFIPS,County Name,State,StateFIPS,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,...,2021-02-02,2021-02-03,2021-02-04,2021-02-05,2021-02-06,2021-02-07,2021-02-08,2021-02-09,2021-02-10,2021-02-11
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,70,71,74,76,77,77,77,77,79,81
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,228,228,233,234,234,234,234,234,239,240
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,40,42,43,44,45,45,45,45,46,46
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,52,52,52,52,53,53,53,53,54,54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,33,33,33,33,33,33,33,34,34,34
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,7,7,7,7,7,7,7,8,8,8
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,12,12,12,12,12,12,12,12,12,12
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,26,26,26,26,26,26,26,26,26,26
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,5,5,5,5,5,5,5,5,5,5

In [62]:
len(deaths[1:]['countyFIPS'].unique())

3143

In [70]:
deaths[1:][cases['State']=='DC']

/home/pratik/.local/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

,countyFIPS,County Name,State,StateFIPS,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,...,2021-02-02,2021-02-03,2021-02-04,2021-02-05,2021-02-06,2021-02-07,2021-02-08,2021-02-09,2021-02-10,2021-02-11
327,0,Statewide Unallocated,DC,11,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
328,11001,District of Columbia,DC,11,0,0,0,0,0,0,...,921,926,932,940,947,952,956,961,965,973

In [66]:
for i in cases[1:]['State'].unique():
    print(i)

AL
AK
AZ
AR
CA
CO
CT
DE
DC
FL
GA
HI
ID
IL
IN
IA
KS
KY
LA
ME
MD
MA
MI
MN
MS
MO
MT
NE
NV
NH
NJ
NM
NY
NC
ND
OH
OK
OR
PA
RI
SC
SD
TN
TX
UT
VT
VA
WA
WV
WI
WY