In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import math
import numpy as np
from datetime import datetime
import plotly.graph_objects as go
from IPython.display import Image

In [2]:
super_dataset = pd.read_csv('../../../../data/stage_I/superDataset.csv')

In [6]:
ny_dataset = super_dataset[super_dataset['State'] == 'NY']

ny_dataset

,countyFIPS,County Name,State,StateFIPS,population,2020-01-22_cases,2020-01-22_deaths,2020-01-23_cases,2020-01-23_deaths,2020-01-24_cases,...,2021-03-13_cases,2021-03-13_deaths,2021-03-14_cases,2021-03-14_deaths,2021-03-15_cases,2021-03-15_deaths,2021-03-16_cases,2021-03-16_deaths,2021-03-17_cases,2021-03-17_deaths
1859,0,Statewide Unallocated,NY,36,0,0,0,0,0,0,...,0,197,0,197,0,199,0,199,0,199
1860,0,New York City Unallocated,NY,36,0,0,0,0,0,0,...,0,197,0,197,0,199,0,199,0,199
1861,36001,Albany County,NY,36,305506,0,0,0,0,0,...,21551,339,21595,339,21645,339,21688,339,21736,339
1862,36003,Allegany County,NY,36,46091,0,0,0,0,0,...,2956,82,2957,82,2959,82,2962,82,2965,82
1863,36005,Bronx County,NY,36,1418207,0,0,0,0,0,...,147155,6062,147592,6062,148043,6089,148599,6102,149574,6110
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1918,36115,Washington County,NY,36,61204,0,0,0,0,0,...,2460,54,2464,54,2471,54,2482,54,2493,54
1919,36117,Wayne County,NY,36,89918,0,0,0,0,0,...,4607,65,4620,65,4631,65,4637,65,4647,65
1920,36119,Westchester County,NY,36,967506,0,0,0,0,0,...,112567,2146,112854,2146,113204,2149,113577,2152,113999,2155
1921,36121,Wyoming County,NY,36,39859,0,0,0,0,0,...,2947,49,2954,49,2958,49,2963,49,2969,49
1922,36123,Yates County,NY,36,24913,0,0,0,0,0,...,1033,26,1036,26,1036,26,1037,26,1039,26

In [4]:
ny_dataset = super_dataset[super_dataset.location == 'New York'].fillna(0)
ny_dataset[['year', 'week', 'day']] = pd.DataFrame(ny_dataset.date.apply(lambda x: datetime.strptime(x, "%Y-%m-%d").isocalendar()).to_list(), index=us_dataset.index)
ny_dataset.head()

AttributeError: 'DataFrame' object has no attribute 'location'

In [ ]:
weekly_data = ny_dataset.groupby(['year', 'week']).mean()[["new_cases", "new_deaths"]].apply(lambda x: np.round(x).astype("int")).reset_index()
weekly_data['date'] = weekly_data.apply(lambda x: datetime.strptime("{0}-{1}-1".format(x[0], x[1]), "%G-%V-%u").date().__str__(), axis=1)
weekly_data.head()

In [ ]:
desc = ny_cases.describe().apply(lambda x: np.round(x).astype('int'))
for i in ['new_cases', 'new_deaths']:
    print("MEAN {0} per WEEK:\t".format(i.upper()), desc[i].loc["mean"])
    print("MEDIAN {0} per WEEK:\t".format(i.upper()), desc[i].loc["50%"])
    for k, v in weekly_data.new_cases.value_counts()[:1].to_dict().items():
        print("MODE {0} per WEEK:\t".format(i.upper()), k, ", frequency:", v)
    print("\n\n")